/* PROYECTO: Formando Campeones
   CICLO 3
   OBJETIVO: Eliminación de paquetes componentes */

DROP PACKAGE BODY PK_ADMINISTRACION;
DROP PACKAGE PK_ADMINISTRACION;

DROP PACKAGE BODY PK_ENTRENAMIENTO;
DROP PACKAGE PK_ENTRENAMIENTO;

DROP PACKAGE BODY PK_AUDITORIAS;
DROP PACKAGE PK_AUDITORIAS;

COMMIT;
