/* PROYECTO: Formando Campeones
   CICLO 4
   OBJETIVO: Eliminación de roles y permisos */

-- REVOCAR PERMISOS DE ADMINISTRADOR
REVOKE EXECUTE ON PK_ADMINISTRACION FROM ADMINISTRADOR;
REVOKE EXECUTE ON PK_ENTRENAMIENTO FROM ADMINISTRADOR;
REVOKE EXECUTE ON PK_AUDITORIAS FROM ADMINISTRADOR;

-- REVOCAR PERMISOS DE ENTRENADOR
REVOKE EXECUTE ON PK_ENTRENAMIENTO FROM ENTRENADOR;

-- ELIMINAR ROLES
DROP ROLE ADMINISTRADOR;
DROP ROLE ENTRENADOR;

COMMIT;
